multinet-app/multinet-client

src/views/WorkspaceDetail.vue
=> Use a computed prop for `tables`

src/components/FileUploadForm.vue
=> Remove the graph upload padding

src/views/NodeDetail.vue
=> Replace "airport" with "node"

src/components/Sidebar.vue, src/components/WorkspaceDialog.vue
=> Fix sidebar scrolling

src/components/FileUploadForm.vue
Depends on https://github.com/multinet-app/multinet-server/pull/354
Closes #21
=> Display an error when uploading to an existing table

src/types.ts, src/views/GraphDetail.vue, src/views/NodeDetail.vue, src/views/TableDetail.vue, src/views/WorkspaceDetail.vue
Update the props definitions in various files to be specific.
=> Fix props declarations

src/components/ItemPanel.vue, src/components/Sidebar.vue
`v-item-action` isn't a vuetify component, so this just updates it to use the one I think was intended.
=> Change v-item-action to v-list-item-action

src/App.vue, src/components/NetworkPanel.vue, src/components/TablePanel.vue, src/views/WorkspaceDetail.vue
=> Remove lingering TODOs and update calls

src/components/AboutDialog.vue
=> Update apidocs href in about panel

netlify.toml, src/App.vue
Adds file configuration for netlify, and adds the ability to specify different environment variables for production builds vs branch previews
=> Add netlify.toml

src/components/LoginMenu.vue, src/store/index.ts
=> Refresh visible workspaces and data on logout

package.json, src/components/FileUploadForm.vue, src/components/TableDialog.vue, yarn.lock
Depends on https://github.com/multinet-app/multinetjs/pull/12
=> Add progress bar to file uploads

src/views/FrontPage.vue
Fixes #92 
I'm open to suggestions on this, but I thought more of a full width approach was nice. Making the top area look more like a hero banner.
=> Fix front page alignment and "banner-ize" hero

package.json, src/App.vue, src/api.ts, src/components/LoginMenu.vue, src/store/index.ts, src/utils/localStorage.ts
Depends on https://github.com/multinet-app/multinet-server/pull/472
Depends on https://github.com/multinet-app/multinetjs/pull/19.
Notable changes:
* Move login logic from `App.vue` to `LoginMenu.vue`
* Add method that checks the URL for an included loginToken, handling it if present.
* Use `userInfo` and `logout` functions of `multinetjs`
* Add interface for storing/retrieving login tokens through localStorage
* Fix incorrect encoding of `return_url` when logging in
=> Replace use of cookies for token storage with localStorage

src/components/TableDialog.vue, src/types.ts, src/utils/files.ts
Recommendation from https://github.com/multinet-app/multinet-client/pull/125#discussion_r498904484. This would clean up the `TableDialog` function a bit.
=> Extract parsing function into utils/files

package.json, src/components/TableDialog.vue, src/main.ts, src/utils/files.ts, yarn.lock
This enables us to use the composition API in the application in general, with a specific example conversion of the `TableDialog` component into composition API.
=> Add Vue Composition API

src/components/TableDialog.vue
I felt it easier to make my recommendations (mostly around the styling/feel of the dialog) as a PR.
=> Recommendations for Column Type Information Dialog

package.json, yarn.lock
This PR wraps up several dependabot alerts into a single set of fixes.
=> Dependabot fixes

.env.default, package.json, src/components/LoginMenu.vue, src/environment.ts, src/main.ts, src/oauth.ts, src/store/index.ts, yarn.lock
This won't work until https://github.com/multinet-app/multinetjs/pull/28 is merged and a new release of multinetjs is cut.
=> Use OAuth login

package.json, yarn.lock
This fixes the currently broken AQL Wizard
=> Bump multinet version to 0.21.3

src/components/NetworkMultiCSVUploadForm.vue
No
I noticed a bug where the network builder wouldn't load. This fixes that issue.
Before:
After:
=> Check for undefined variables in the template in NetworkMultiCSVUploadForm

package.json, src/views/AQLWizard.vue, yarn.lock
Client change for https://github.com/multinet-app/multinet-api/pull/139
Also closes #119
=> Add bind vars to AQL query UI

package.json, src/components/Sidebar.vue, src/components/WorkspaceDialog.vue, src/views/WorkspaceDetail.vue, yarn.lock
Closes #251 
Bumps vue-router to ^3.6.0 and uses the vue 2.7 / vue 3 syntax for router calls.
N/A
=> Bump vue router

netlify.toml
No
Google Analytics is migrating users from universal analytics to GA4. Updating the tag here should be all that's needed, but we need to verify that.
N/A
TODOs:
=> Update google analytics tag to GA4 version

src/components/DownloadDialog.vue
Closes https://github.com/multinet-app/multinet-api/issues/144
This allows users to download networks and tables as JSON objects. Currently, these formats are incompatible with our uploader, but I'm planning to make some changes to allow them to be uploaded.
No UI changes, this is just under the hood downloading javascript changes
No
=> Re-enable downloading networks and tables as json objects

package.json, src/components/TableDialog.vue, src/utils/files.ts, yarn.lock
No
This allows a user to upload a table using JSON, instead of just csv
The UI is the same as uploading a csv
TODOs:
=> Allow JSON table uploads

src/environment.ts, src/main.ts
No
This better handles the local storage, cookies, and their invalidation. 
N/A
TODOs:
=> Fix issues with invalidating cookies and restoring logins

package.json, src/components/SessionPanel.vue, src/components/Sidebar.vue, src/components/TablePanel.vue, src/store/index.ts, src/views/FrontPage.vue, yarn.lock
Depends on 
Helps towards https://github.com/orgs/multinet-app/projects/13/views/1?pane=issue&itemId=32535261
Sidebar changes:
Sessions changes:
TODOs:
=> Organize the sidebar workspaces into starred and not starred
