src/components/FileUploadForm.vue
This can happen if, e.g., someone renames a non-CSV file with a .csv extension then attempts to upload it.
Depends on https://github.com/multinet-app/multinet-server/pull/355
Closes #20
=> Display an error if uploaded file can't be read as CSV

src/components/DeleteGraphDialog.vue, src/components/DeleteTableDialog.vue, src/components/DownloadDialog.vue, src/components/GraphDialog.vue, src/components/ItemPanel.vue, src/components/Sidebar.vue, src/components/TableDialog.vue
@waxlamp - I guess I need some help with the logic of this. For now it's just icons, but I want to be able to use the existing `DeleteGraphDialog.vue`, `DeleteTableDialog.vue` and `DeleteWorkspaceDialog.vue`. Couldn't quite figure out the logic to link it up, because the icon needs to be different. `delete_sweep` is being used for deleting selections and just `delete` will be used for individual items.
Closes #12
=> Improved UX for deleting Workspaces/Tables/Graphs

package.json, src/components/FileUploadForm.vue, src/components/TableDialog.vue, src/utils/files.ts, yarn.lock
Fixes #15.
Depends on https://github.com/multinet-app/multinetjs/pull/7.
Depends on https://github.com/multinet-app/multinet-server/pull/356
=> Remove FileUploadForm from TableDialog, add csv key options

src/views/WorkspaceDetail.vue
Currently, when loading a workspace, there's a period of time where no graphs or tables appear, as that data is being fetched. This improves the UI a bit by adding a progress bar while this is happening.
=> Add loading progress bar

src/components/DeleteGraphDialog.vue, src/components/DeleteTableDialog.vue, src/components/DeleteWorkspaceDialog.vue
This fixes a bug I just found/had encountered when doing the vuex stuff.
Before this change, this.$emit('deleted') would run right after
the forEach loop had finished kicking off asynchronous calls,
before they had finished. This lead to the fetching of new data
to happen in the middle of these deletion calls, which returned
incorrect/incomplete results.
=> Fix deletion api calls to order properly

src/components/DownloadDialog.vue, src/components/NetworkPanel.vue, src/components/TablePanel.vue, src/views/WorkspaceDetail.vue
This probably just slipped through the cracks when we split up `ItemPanel`. If you'll notice, before this change, downloading a selection of tables/networks would keep the selection afterwards. 
Also, if you were to navigate to a different workspace after making a selection, that same selection would still be active on the second workspace, and would show up in the download/delete dialog.
This PR addresses both of these issues.
=> Fix downloaders and lingering selection

src/App.vue, src/appregistry.json, tsconfig.json
This PR does two things:
- switches the "app config" to be a build time, static operation
- changes the app config defaults to link to the view apps on Netlify (where they are now configured to deploy to automatically)
=> Update app config to link to Netlify

src/appregistry.json, src/views/FrontPage.vue
Reduces the number of places where we manually define the link to the nodelink and adjacency matrix applications
=> Use appregistry.json for the quick links

src/App.vue
This fixes an error introduced in #80 during a merge commit.
The app was not showing that a logged in user was actually logged in; this solves that problem by forcing a check of the logged in user's information upon starting the app.
=> Bootstrap the app with current logged in user info

package.json
multinetjs 0.13.0 includes sending of credentials with all requests,
which is needed in order for the client to properly display the
logged-in user's readable workspaces.
This PR depends on https://github.com/multinet-app/multinetjs/pull/10.
=> Update multinetjs version to 0.13.0

src/components/WorkspaceDialog.vue
This PR also removes the "intro" popover, as (1) it has become sort of annoying and (2) its advice no longer applies.
Since the way to really get started with this app is to create an account and log in, I'd like to find a UI design principle that makes the login mechanism more obvious and inviting (currently it's hidden behind a general "user account" badge).
=> Disable "new workspace" button when user is not logged in

.eslintrc.js, package.json, src/components/DownloadDialog.vue, src/components/FileUploadForm.vue, src/router.ts, src/utils/files.ts, src/views/AQLWizard.vue, src/views/WorkspaceDetail.vue, yarn.lock
Fixes #106.
This adds the UI for several key features:
* Running AQL queries
* Viewing the result of AQL queries
* Creating tables from the result of AQL queries
A new dependency is added, `vue-json-pretty`, which allows for viewing the JSON results in a clean way.
=> AQL Table Creation UI

src/views/GraphDetail.vue, yarn.lock
Closes #123
Adds logic to pass the login token from the main client to the vis apps via the querystring. 
I also had to update yarn.lock, since it wasn't updated in #122 after the version was bumped.
=> Pass login tokens to the vis apps

yarn.lock
This modifies the selfsigned version to use 1.10.8, which uses the new version of node-forge.
This type of modification of the yarn.lock file by hand is not recommended and I wonder if we should just do the yarn upgrade command that I originally had.
=> Upgrade @vue/cli-service to fix node-forge vuln

src/components/TableDialog.vue, src/types.ts, src/utils/files.ts
This PR adds a `boolean` semantic type to the ones detected at CSV upload time.
This works by detecting whether a column has exactly two unique values, and whether those two values are one of several possible pairs of boolean-indicative values. These include the strings `0` and `1` but also several of the YAML-compliant boolean values.
Some things I need feedback on:
- Currently, the heuristic does not allow for mix-and-match between the possible signal words--e.g., a column with `yes` for true and `0` for false, or a mix of `yes` and `true` for true, will NOT be detected as a boolean column. **Should we allow for a mix-and-match approach, or restrict to just a single pair of words?** (If we support "mix-and-match" then the heuristic will need to change slightly, but this is not a big …
=> Add a "boolean" semantic type detection

src/views/AQLWizard.vue, src/views/FrontPage.vue, src/views/GraphDetail.vue, src/views/NodeDetail.vue, src/views/TableDetail.vue, src/views/WorkspaceDetail.vue
This is in response to console warnings explaining that `<v-content>` is deprecated.
@jtomeck, could you verify that this change is the correct way to do things? I couldn't find a migration guide addressing this specifically, so I just followed the advice in the warning message itself (which just says to use `<v-main>` instead).
=> Replace `<v-content>` with `<v-main>`

src/components/TableDialog.vue, src/utils/files.ts
This uses @jtomeck's design for a preview table within a stepper to (1) select a CSV file to upload and (2) examine a sample of the data and set up column data types before (3) uploading the table to Multinet.
@jtomeck: I need help making my use of Vuetify have the right styles to match up to your design. For example:
- the colors are wrong
- the `<v-select>`s look ugly as sin
- no finish flag in the stepper
- the stepper got reduced to only two steps
Let me know what you think.
Closes #134
=> Add an upload preview table with column type selectors

package.json, src/components/TableDialog.vue, src/utils/files.ts, yarn.lock
This PR makes use of https://github.com/multinet-app/multinetjs/pull/22.
This uses the updated multinetjs library to send column type information at table upload time.
Depends on https://github.com/multinet-app/multinetjs/pull/22 being merged and released.
Depends on #136.
=> Add column type information to table creation call

package.json, src/views/TableDetail.vue, yarn.lock
This PR makes use of https://github.com/multinet-app/multinetjs/pull/23 to display the semantic types in the header row of the table view, if they exist.
@AlmightyYakob, could you make sure the code looks ok?
@jtomeck, could you take a look at design issues? The way I've done it works but I can tell it doesn't look/feel great.
Eventually, after migrations are implemented, we can dump the "if it exists" logic, since we can be confident that the type metadata will always exist.
TODO
=> Display semantic types in table view

src/components/DeleteTableDialog.vue, src/components/TableDialog.vue
Closes #150
This fixes the bug in #150 that meant that the table upload dialog would not update between 2 table uploads.
I also noticed that the delete dialog wouldn't reset after a success, so I updated that to clear itself out and reset.
=> Reset modals on successful completion

src/components/NetworkPanel.vue, src/components/Sidebar.vue, src/components/TablePanel.vue, src/views/GraphDetail.vue, src/views/NodeDetail.vue, src/views/TableDetail.vue, src/views/WorkspaceDetail.vue
Closes #147
Uses skeleton loaders across the app to give a more seamless experience. This new functionality means that the app doesn't load into an empty state and flip to the correct values.
There are a couple of issues I have regarding how many skeleton loaders to use for each piece, and there doesn't seem to be a way to change the color of the loaders. The number of loaders is a potential issue in most places and I'd like some feedback on how many you think I should use. Also, the colors are slightly different from the loaded version in just a couple of places, namely the NodeDetail panel and the table view when using skeleton loaders.
Let me know what you think. I'll add some screenshots below, but the deploy preview should give you a good example of how it will work in practice.
One …
=> Add skeleton loaders across the app

package.json, yarn.lock
There's a CVE out for the version of axios included in this project, but the codebase doesn't seem to use axios at all. If this is merged, we can close #148.
=> Remove axios dependency

src/store/index.ts, src/views/TableDetail.vue
This PR changes how the responses from the server are handled to access table and workspace names properly.
=> Fix workspace and table handling

src/components/DeleteTableDialog.vue, src/components/LoginMenu.vue, src/environment.ts, src/views/GraphDetail.vue, src/views/NodeDetail.vue, src/views/TableDetail.vue
This PR changes how the client interacts with the data provided by multinetjs to display information about networks and nodes properly.  It also includes the following changes to adjust to the new backend:
- displaying user's initials
- changing to the appropriate localhost server address
- adjusting how table-network dependencies are calculated to warn users when they delete tables
- checking that tables aren't empty before attempting to display their rows
This PR works in conjunction with changes found in the [new-return-types](https://github.com/multinet-app/multinetjs/tree/new-return-types) branch of multinetjs
Resolves #161
=> Finish porting client to new backend

.github/workflows/main.yml
Previously, CI would only run on PRs and pushes to `master`.
=> Always run CI

src/components/DeleteTableDialog.vue, src/components/PermissionsDialog.vue, src/utils/permissions.ts, src/views/NodeDetail.vue
Closes #177 
This pull request updates the `multinet-client` to be compatible with the new Girder4 back end API. It is dependent on changes 
present in the [girder4-permissions branch](https://github.com/multinet-app/multinetjs/tree/girder4-permissions) of the `multinetjs` repository. 
Changes include:
1. Updating property access on objects of type `UserSpec` to conform with the Django `User` model
2. Cleaning up some linting issues by adding typing and  a null check
=> Ensure compatability with girder4 permission endpoints

src/components/FileUploadForm.vue, src/components/GraphDialog.vue, src/components/GraphUploadForm.vue, src/components/TableDialog.vue, src/types.ts
Update the client to pass additional information to multinetjs to allow for table and network uploads using the S3 File Field client.
This PR works in conjunction with the s3ff branch of [multinetjs](https://github.com/multinet-app/multinetjs/tree/s3ff)
Should be merged after #178.  Commits pertinent to this PR are 9e1d1df, 86dd4fc and fcaec43, which make changes to FileUploadForm.vue and TableDialog.vue (all other commits are for changes addressed in #178).
**Edit: Now that #178 is merged, all commits associated with this PR are relevant.**
=> Support S3 File Field Upload functionality

netlify.toml
This updates the `netlify.toml` to point the netlify deploys to the new API. Once we setup a testing app for new API, we can change the deploy previews to point to that testing app, instead of production.
=> Update netlify.toml to point to new api deploy

src/components/DeleteNetworkDialog.vue, src/components/DeleteTableDialog.vue, src/components/DownloadDialog.vue, src/components/NetworkCreateForm.vue, src/components/NetworkDialog.vue, src/components/NetworkPanel.vue, src/components/NetworkUploadForm.vue, src/router.ts, src/store/index.ts, src/types.ts, src/views/AQLWizard.vue, src/views/NetworkDetail.vue, src/views/NodeDetail.vue, src/views/WorkspaceDetail.vue, test/e2e.test.js
Replaces all use of graph(s) with network(s) to maintain continuity across the frontend.  This includes the renaming of: 
- GraphDetail.vue
- DeleteGraphDialog.vue
- GraphCreateForm.vue
- GraphDialog.vue
- GraphUploadForm.vue
The only places where graph has not been replaced are in the urls which link to the visual applications (where a similar change has not been made).
Works in conjunction with the graph-to-network branch of [multinetjs](https://github.com/multinet-app/multinetjs/tree/graph-to-network).
=> Replace all use of 'graph(s)' with 'network(s)' for consistency

src/views/WorkspaceDetail.vue
Removes the use of a destructuring assignment for the data variable and extracts the new name of the workspace to account for the new Workspace return type of renameWorkspace() and support the use of the new workspace renaming endpoint.
Works in conjunction with the rename-workspace branches of [multinetjs](https://github.com/multinet-app/multinetjs/tree/rename-workspace) and [multinet-api](https://github.com/multinet-app/multinet-api/tree/rename-workspace).
=> Refactor client to work with new workspace renaming endpoint

package.json, src/components/DeleteNetworkDialog.vue, src/components/DeleteTableDialog.vue, src/components/NetworkPanel.vue, src/components/PermissionsDialog.vue, src/components/TablePanel.vue, src/store/index.ts, src/utils/permissions.ts, src/views/AQLWizard.vue, src/views/WorkspaceDetail.vue, yarn.lock
Closes #140 
This PR updated the client application code to utilize the new API endpoint `GET /api/workspaces/{workspace}/permissions/me/`.
Specifically, the following changes are made:
1. Update the Vuex store to track the current user's permission on the currently selected workspace
2. Add a `getter` to the Vuex store to check permission level. This includes a new utility function to help with permission checking
3. Use this new `getter` in the `PermissionDialog` component instead of the function defined in `utils/permission.ts`
4. Update `NetworkPanel` and `TablePanel` to use the new `getter` to enable/disable functionality based on permission level
5. Remove use of `selection` parameter in `DeleteTableDialog` and `DeleteNetworkDialog`, as its use was redundant
=> Enable network and table creation/deletion based on permissions

src/utils/files.ts
Closes #195
Instead of parsing the whole dataset to guess the types for the columns, we can just parse the first thousand rows. This helps the run time -- it's basically instant. That means the preview rows will have loaded by the time you're looking at type specifying page in the stepper.
I tried to use the papaparse `preview` [option](https://www.papaparse.com/docs#config), but I think the `step` callback overrides that. To get around that issue I implemented a counter that will trigger the parser to abort when we hit that number.
The types suggested were identical on my test set with either so I think this is pretty robust.
We'll need some better error UI in the future to alert users to any parsing issues, but this has never been implemented and shouldn't slow this PR down.
=> Guess the column types from the first 1000 rows

src/views/FrontPage.vue
Closes #90
Will require equivalent PRs on the clients
Looks most of the querystrings were already updated, but there were a few spots that we missed. I've updated them here and will update the vis apps so that when we transition to the new API, everything is working as we expect
=> Network-in-querystring

src/components/DeleteTableDialog.vue
Found this when deleting a bunch of tables. With the question mark, it's unclear whether that is a part of the string to be typed or not.
The phrase is clearly not a question so I removed it
=> Remove an extra question mark from the delete dialog

src/components/DeleteNetworkDialog.vue, src/components/DeleteTableDialog.vue, src/components/DeleteWorkspaceDialog.vue, src/components/LoginMenu.vue, src/components/NetworkCreateForm.vue, src/components/TableDialog.vue, src/components/WorkspaceOptionMenu.vue, src/store/index.ts, src/utils/files.ts, src/views/NetworkDetail.vue, src/views/NodeDetail.vue, src/views/TableDetail.vue, src/views/WorkspaceDetail.vue
As I've been using the app I've noticed many small UX issues that make the app harder to use. This is a first attempt at addressing some of the more heinous ones:
- #194 Handle user initals better if they don't exist
- #190 Clear deletion confirmation text when the require phrase changes and on successful delete
- Sort all networks, tables, and workspaces alphabetically
- Only show skeletons when they're needed in table detail
- Use the same menu with permissions and AQL editor wherever the menu icon appears
- Disable the create network and table buttons when a user has clicked them (I've seen users click multiple time creating multiple upload objects)
- Fix up the logic for file upload handling so it clears properly when a file is removed/added. This change improves the code readability …
=> Address various papercuts in the UI/UX

src/views/TableDetail.vue
Closes #32
Use the vuetify pagination type instead of the same definition in our code. This was flagged for removal with vuetify>= 2.2 and it seems our yarn.lock puts us at 2.5.8.
If I need to bump the minimum version in package.json from 2.1.5 to 2.2.0, let me know.
=> Prefer vueitfy DataPagination type

.github/workflows/main.yml
Nope, it's just an improvement to help us reduce redundant code across the repos.
I've added an action in multinet-app/.github that handles this logic. The gameplan is to prefer using that to workflow files in each individual repo to provide more consistent testing logic.
N/A
TODOs:
=> Use the organization action for linting

package.json, src/store/index.ts, src/types.ts, src/views/WorkspaceDetail.vue, yarn.lock
Closes #174
This PR does 3 things:
1. Converts the workspace detail component to composition API (there's one small wrinkle with vue.router that I had to work around. See [here](https://github.com/multinet-app/multinet-client/pull/210/commits/4d45316edcaf1c3f61519487604ffb8b33058496#diff-800e682df700e57321ffeca2830a5d4fb044ce70407890f05188386a94ac54c2R136-R138)) (See code review for updated approach)
2. Gets all uploads from the API using a new route added in multinetjs
3. Adds an info alert to the workspace detail view when there are uploads that are not finished
With upload in progress:
Without upload in progress (same as before):
TODOs:
=> Show upload status in workspace detail view

package.json, src/App.vue, src/components/AExt.vue, src/components/AboutDialog.vue, src/components/AboutText.vue, src/components/DeleteNetworkDialog.vue, src/components/DeleteTableDialog.vue, src/components/DeleteWorkspaceDialog.vue, src/components/DownloadDialog.vue, src/components/LoginMenu.vue, src/components/NetworkCreateForm.vue, src/components/NetworkDialog.vue, src/components/NetworkMultiCSVUploadForm.vue, src/components/NetworkPanel.vue, src/components/NetworkUploadForm.vue, src/components/PermissionsDialog.vue, src/components/Sidebar.vue, src/components/TablePanel.vue, src/components/WorkspaceDialog.vue, src/main.ts, src/utils/use.ts, src/views/AQLWizard.vue, src/views/FrontPage.vue, src/views/NetworkDetail.vue, src/views/NodeDetail.vue, src/views/TableDetail.vue, src/views/WorkspaceDetail.vue, yarn.lock
Depends on #246 
This large PR migrates all components over to the composition API.
There were a couple of issues that I ran into when trying to do this conversion that I had to work around. The main one was that `vue-router` doesn't support the composition API on vue 2.x. As such, I have to interact with the router in cumbersome ways (through getCurrentInstance with lots of null checks). This will be fixed in a final vue 2.x compatible release of `vue-router`, when vue-router#3760 is addressed. I will make an issue to track this change.
N/A
TODOs:
=> Migrate all components to the composition API

src/components/NetworkPanel.vue, src/components/Sidebar.vue, src/components/TablePanel.vue, src/types.ts
Depends #247 
Closes #245
Moves the `CheckboxTable` type into types.ts, instead of redefining it in 3 separate places.
N/A
No
=> Move checkbox tables type to types.ts

src/components/NetworkMultiCSVUploadForm.vue
Closes #258 
With this change, you can creating a network in the UI with the following data (not possible before)
Edge table:
```
source,target
1,2
1,3
2,3
```
Node table
```
id,name
1,jack
2,john
3,james
```
=> Allow source/target column sharing

package.json, src/components/TableDialog.vue, src/utils/files.ts, yarn.lock
Closes #7 
This change adds a user-specifiable csv delimiter and quote character. 
The csv analysis that already runs will suggest a delimiter, so I grabbed that as the default recommendation. When the user changes the delimiter and selects a different delimiter, the analysis is re-ran so that the preview is updated.
The quote character is a selection between a couple of options (`"` and `'`). Similarly, this re-runs the analysis so that the preview is updated accordingly.
CSV2 before:
CSV2 after:
Upload UI changes:
TODOs:
=> Add user-specifiable csv delimiters and quote characters

src/components/TableDialog.vue
Adds the tab (\t) delimiter and refactors delimiterOptions to allow different names and values in papaparse.
=> Tab delimiter and delimiterOptions

src/main.ts
This PR implements a shared login setup using a "domainless" cookie to allow the vis apps to read login credentials from multinet.app's cookie storage.
=> Use an intradomain cookie to communicate login credentials

package.json, src/main.ts, yarn.lock
This PR changes the use of private functions to those from multinet-app/multinetjs#77.
Marking this as draft because once multinetjs is released, this branch will need to update the dependent multinetjs version before it can be reviewed and merged.
(See also https://github.com/multinet-app/multilink/pull/347.)
=> Use shared login functions from multinet library

src/components/NetworkCreateForm.vue, src/components/NetworkMultiCSVUploadForm.vue, src/components/NetworkUploadForm.vue, src/components/TableDialog.vue, src/utils/validation.ts
No
We currently allow illegal Arango names, which leads to network or table upload/creation errors. This is only told to the use after a failed upload. The Arango naming conventions are listed [here](https://www.arangodb.com/docs/stable/data-modeling-naming-conventions-collection-and-view-names.html).
To fix this, I added name validation and some error messages that show the user what is wrong before the creation/upload fails. This is much more robust than what we had previously.
No
=> No illegal object names for Arango

package.json, src/components/WorkspaceOptionMenu.vue, src/views/WorkspaceDetail.vue, yarn.lock
Closes #307 
This PR adds the ability to fork a workspace provided the user has access to the workspace.
The fork option is found under the workspace menu options.
Once forked, the user will be redirected to the new workspace.
TODOs:
=> Workspace Fork
